name 'agate-nginx'
version '0.0.1'
source 'git://github.com/leventyalcin/agate-nginx.git'
author 'Levent Yalcin'
license 'Apache 2.0'
summary 'php Module'
description 'nginx'
project_page 'git://github.com/leventyalcin/agate-nginx'
